# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/x3/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/x3

PRODUCT_COPY_FILES += \
    vendor/realme/x3/proprietary/product/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/realme/x3/proprietary/product/etc/permissions/com.android.hotwordenrollment.okgoogle.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.hotwordenrollment.okgoogle.xml

PRODUCT_PACKAGES += \
    PowerOffAlarm \
    HotwordEnrollmentOKGoogleWCD9340 \
    SoterService \
    com.android.hotwordenrollment.common.util \
    vendor.qti.hardware.alarm-V1.0-java
